name: LibelulaAutoShop
version: "1.0.3-SNAPSHOT"
main: me.libelula.autoshop.Main
description: Libelula Automatic Shop Creation
author: Diego Lucio D'Onofrio <ddonofrio@member.fsf.org>
website: http://libelula.me
depend: [Essentials, ChestShop, Vault]
    
commands:
    autoshop:
        description: Toggles Shop creation.
        usage: /autoshop [on|off] <quantity> <price>
        permission: autoshop.create

permissions:
    autoshop.*:
        description: Gives access to all.
        children:
            autoshop.create: true
